### PR TITLE
Fix import ordering

### PR DESCRIPTION
**Pull request by jcox-dev**
Running PyCharm's optimiser ✨

### CODE REVIEW

**Review by benjefferies — APPROVED** [review]
I wonder if it's just worth integrating https://github.com/ambv/black

**Review by benjefferies — APPROVED** [review]
I wonder if it's just worth integrating https://github.com/ambv/black

**Comment by jcox-dev** [comment]
@benjefferies in the backlog 👍

**Review by shahi645 — APPROVED** [review]

**Comment by jcox-dev** [comment]
[Cleanup order of imports in Python services](https://trello.com/c/ulBo8OUj/259-cleanup-order-of-imports-in-python-services)

**Pull request merged**
