### PR TITLE
[Tbl3] separate tests for respondents

### PR DESCRIPTION
**Pull request by jcox-dev**
This will be the first steps for removing/refactoring the respondent endpoints in the party service.

Initial work includes: refactoring tests by isolating respondent-related activity and increasing test coverage overall where possible.

### CODE REVIEW

**Comment by jcox-dev** [comment]
Remaining work for this PR is to rework the rest of the tests in [test_respondent_controller.py](https://github.com/ONSdigital/ras-party/pull/76/files#diff-c94342f17399508ed4c3a60c3d3025f0).
 
(Admittedly, this file is currently a bit of a misnomer as the respondent controller only handles a couple of endpoints but the consideration is there to hint at next moving the functionality from [account_controller.py](https://github.com/ONSdigital/ras-party/blob/master/ras_party/controllers/account_controller.py) to [respondent_controller.py](https://github.com/ONSdigital/ras-party/blob/master/ras_party/controllers/respondent_controller.py)).

**Review by JamesGardiner — APPROVED** [review]

**Comment by emilioward** [comment]
[Enrolment technical journey refinement (TBL)](https://trello.com/c/hBa7HT2O/3-enrolment-technical-journey-refinement-tbl)

**Comment by tej99** [comment]
@jcox-dev i'm not sure if moving functionality from account_controller.py to respondent_controller.py will help with enrolment refinement. The reason for splitting the functionality over the two files was that all the functionality in account_controller.py relates to the enrolment process, whereas the functionality in respondent_controller.py will stay in party service weather enrolment process stays in the party service or not.

**Comment by jcox-dev** [comment]
@tej99 understood. We should probably review what is required to remain in the party service and what can and should be moved into a separate account management / enrolment service.

**Review by tej99 — APPROVED** [review]

**Pull request merged**
